### ISSUE TITLE
Macros running

### ISSUE THREAD

**Issue by Chomikmarkus** [psyc0de/OffensiveProjects#1]
Hello!
Trying to reproduce this! Using Your macro source after activating it, nothing happens! When i run macros manually like  "run Auto_Open it downloads file and displays messagebox, but no further actions! 
BTW nice blog post!

**Comment by psyc0de** [comment]
[*] One known issue is that if the file exists in folder then func2 does not trigger, which is what causes the system to reboot. You will need to delete the file from the startup folder with each test.
[*] I also recommend removing the comments, some of them were made after the fact and they might be causing the function to not execute properly. If the comment is not showing as green text then it may be causing you issues.
[*] For testing I remove or comment out the sleep option, as it lasts 5 minutes.
